[tool.poetry]
name = "envi"
version = "0.1.0"
description = "Poetry environment demo project"
authors = ["Your Name <you@example.com>"]

# IMPORTANT: disables package installation mode (fixes your error)
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.32.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
